### ISSUE TITLE
Error when calling the function "get_claim_value"

### ISSUE THREAD

**Issue by kwegener1** [arun11299/cpp-jwt#48]
Hello,
I'm in it and testing your library. The decoding worked. Now I would like to read out a value via the function get_claim_value().

`std::error_code ec;`
`auto decodeObj = jwt::decode(strFeatures.toStdString(), algorithms({"RS256"}), ec, secret(keyPublicKey.toStdString()));`

`jwt::string_view claimName = "Webvisu";`
`auto claimValue = decodeObj.payload().get_claim_value(claimName);`
`std::cout << claimValue << std::endl;`

I get the following error:
![image](https://user-images.githubusercontent.com/51323974/58801573-31379800-860b-11e9-9b05-7e5a37d3c1bb.png)

Next I tested the following:
`jwt::string_view claimName = "Webvisu";`
`auto claimValue = decodeObj.payload().get_claim_value<const jwt::string_view>(claimName);`
`std::cout << claimValue << std::endl;`

And get this error:
![image](https://user-images.githubusercontent.com/51323974/58801952-4234d900-860c-11e9-92c8-eed79253257d.png)

**Comment by arun11299** [comment]
Just seeing it now. I will take a look at it and get back.

**Comment by arun11299** [comment]
The first error is because you need to explicitly provide the template parameter. There is no type deduction happening there as the type 'T' is not being used as the function argument.

As for the second case, its the nlohmann json library having some issue in supporting jwt::string_view. I will have to look into it. By that time, can you try doing:

```
auto claimValue = decodeObj.payload().get_claim_value<std::string>(claimName);
```

**Comment by kwegener1** [comment]
It works!
